import org.apache.tools.ant.taskdefs.optional.depend.Depend
import org.gradle.internal.impldep.org.apache.commons.codec.language.bm.Lang


/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
}

group = "fr.morphium"
version = "0.0.1"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

subprojects {
    apply(plugin = "java-library")

    group = parent!!.group
    version = parent!!.version

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly("org.projectlombok:lombok:1.18.34")
        annotationProcessor("org.projectlombok:lombok:1.18.34")

        compileOnly("org.jetbrains:annotations:24.1.0")
    }

    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
    }
}